const $=id=>document.getElementById(id), esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v==null?'—':Number(v).toLocaleString(), day=v=>v?v.slice(0,10):'—';
let state, dataset='1k', revision=0, result=null, jobs=[], page='overview';
const titles={overview:'Overview',history:'Listening history',studio:'Recommendation studio',dormant:'Dormant favorites',runs:'Run activity'};
function notice(message,error=false){$('notice').hidden=!message;$('notice').textContent=message;$('notice').className=error?'error':'';}
async function api(url,body){const res=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':state.token},body:JSON.stringify(body)}:{});const data=await res.json();if(!res.ok)throw Error(data.error||'Request failed');return data;}
function show(name){if(!titles[name])name='overview';page=name;document.querySelectorAll('.page').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('nav button').forEach(el=>el.classList.toggle('selected',el.dataset.page===name));$('breadcrumb').textContent=titles[name];history.replaceState(null,'','#'+name);notice('');if(name==='runs')poll();}
document.querySelector('.brand').onclick=e=>{e.preventDefault();show('overview');};
document.querySelectorAll('[data-page],[data-go]').forEach(el=>el.onclick=()=>show(el.dataset.page||el.dataset.go));
function readiness(){const d=state.datasets[dataset],i=d.ingest,m=d.matrix;$('stats').innerHTML=[['Listening records',i?.clean_rows,'Clean source records'],['Listeners',i?.users,'Across the dataset'],[dataset==='1k'?'Tracks':'Artists',i?.items,'Canonical catalog items'],['Training pairs',m?.observed_pairs,'Observed preferences']].map(([label,n,sub])=>`<div class="stat"><label>${label}</label><strong>${fmt(n)}</strong><small>${sub}</small></div>`).join('');$('readiness').innerHTML=[['Dataset snapshot',!!i],['Preference matrix',!!m],['Artist tags',state.tags_available],['Temporal history',dataset==='1k'&&!!i]].map(([label,ready])=>`<div class="status-line"><span>${label}</span><span class="badge ${ready?'':'pending'}">${ready?'Available':'Unavailable'}</span></div>`).join('');$('generate').disabled=dataset!=='1k'||!m||jobs.some(j=>j.status==='running');$('dormant-submit').disabled=dataset!=='1k'||!i;$('tag-note').textContent=dataset!=='1k'?'The dual-memory studio uses timestamped 1K listening events. Select Last.fm 1K to generate a mix.':state.tags_available?'Tag assignments are filtered before the historical cutoff. Nostalgia requires shared active-context tags.':'Artist tags are not available locally. Automatic mode will use discovery only; nostalgia needs real tag evidence.';}
async function users(q=''){const rev=revision;try{const data=await api('/api/users?'+new URLSearchParams({dataset,q}));if(rev!==revision)return;$('users').innerHTML=data.users.map(r=>`<option value="${esc(r.user_id)}"></option>`).join('');if(!q)for(const id of ['history-user','studio-user','dormant-user'])$(id).value=data.users[0]?.user_id||'';}catch(e){notice(e.message,true);}}
let searchTimer;['history-user','studio-user','dormant-user'].forEach(id=>$(id).addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>users(e.target.value),250)}));
$('dataset').onchange=async()=>{dataset=$('dataset').value;revision++;result=null;$('export').hidden=true;for(const prefix of ['history','dormant']){$(prefix+'-results').innerHTML='<div class="empty">Choose a listener to explore this dataset.</div>';$(prefix+'-summary').textContent='';}$('mix-results').innerHTML='<div class="empty">Generate a mix or open a completed run.</div>';$('mix-meta').textContent='';readiness();await users();};
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;}
function track(row){return `<strong>${esc(row.track||row.track_name||row.artist||row.artist_name||row.item_id)}</strong><small>${esc(row.artist||row.artist_name||'')}</small>`;}
async function formRequest(event,button,task){event.preventDefault();button.disabled=true;notice('Reading the local snapshot…');const rev=revision;try{await task(rev);if(rev===revision)notice('');}catch(e){notice(e.message,true);}finally{button.disabled=false;readiness();}}
$('history-form').onsubmit=e=>formRequest(e,e.submitter,async rev=>{const data=await api('/api/history?'+new URLSearchParams({dataset,user:$('history-user').value}));if(rev!==revision)return;$('history-summary').textContent=`${fmt(data.total_plays)} plays · ${fmt(data.total_items)} items · Top ${data.rows.length} shown`;$('history-results').className='';$('history-results').innerHTML=table(['Track / artist','Plays','Recent plays','Last played'],data.rows.map(r=>`<tr><td>${track(r)}</td><td>${fmt(r.play_count)}</td><td>${fmt(r.active_plays)}</td><td>${day(r.last_played_at)}</td></tr>`));});
$('dormant-form').onsubmit=e=>formRequest(e,e.submitter,async rev=>{const data=await api('/api/dormant?'+new URLSearchParams({dataset,user:$('dormant-user').value,days:$('dormant-days').value,threshold:$('dormant-threshold').value}));if(rev!==revision)return;$('dormant-summary').textContent=`${fmt(data.total)} eligible dormant tracks · Showing ${data.rows.length} · Measured before 1 May 2009`;$('dormant-results').className='';$('dormant-results').innerHTML=data.rows.length?table(['Track / artist','Historical plays','Days quiet','Last played'],data.rows.map(r=>`<tr><td>${track(r)}</td><td>${fmt(r.historical_plays)}</td><td>${fmt(r.days_dormant)}</td><td>${day(r.last_played_at)}</td></tr>`)):'<div class="empty">No tracks meet this window and play threshold. Try a different listener or threshold.</div>';});
function alphaLabel(){$('alpha').disabled=$('auto-alpha').checked;$('alpha-help').textContent=$('auto-alpha').checked?'The blend adapts to the share of recent tracks first heard in the active window.':'Your discovery weight stays fixed; the remaining weight goes to nostalgia.';$('alpha-label').textContent=$('auto-alpha').checked?'Automatic balance':`${$('alpha').value}% discovery / ${100-$('alpha').value}% nostalgia`;}
$('auto-alpha').onchange=alphaLabel;$('alpha').oninput=alphaLabel;
$('studio-form').onsubmit=async e=>{e.preventDefault();$('generate').disabled=true;try{await api('/api/jobs',{user:$('studio-user').value,k:Number($('mix-size').value),alpha:$('auto-alpha').checked?null:Number($('alpha').value)/100,recent_days:Number($('recent-days').value),min_historical_plays:Number($('min-plays').value),half_life_days:Number($('half-life').value)});show('runs');notice('Your run has started. You can explore history while it works.');await poll();}catch(error){notice(error.message,true);}finally{readiness();}};
async function poll(){try{const data=await api('/api/jobs');jobs=data.jobs;$('running-count').textContent=jobs.filter(j=>j.status==='running').length||'';if(jobs.length){const open=new Set([...document.querySelectorAll('.job details[open]')].map(el=>el.dataset.id));$('jobs').className='';$('jobs').innerHTML=jobs.map(j=>`<article class="job"><div class="row"><div><h3>Recommendation mix</h3><div class="fine">${esc(j.user)} · ${esc(j.created.slice(0,16).replace('T',' '))} UTC · ${j.settings.k} tracks requested</div></div><span class="badge ${j.status==='completed'?'':'pending'}">${esc(j.status)}</span></div>${j.error?`<p>${esc(j.error)}</p>`:''}<details data-id="${j.id}" ${open.has(j.id)?'open':''}><summary>View progress log</summary><pre>${esc(j.log)}</pre></details>${j.result_available?`<button class="secondary" data-result="${j.id}">Open mix and explanations ↗</button>`:''}</article>`).join('');document.querySelectorAll('[data-result]').forEach(button=>button.onclick=async()=>{try{result=await api('/api/jobs/'+button.dataset.result+'/result');show('studio');renderMix();}catch(e){notice(e.message,true);}});}if(state)readiness();}catch(e){if(page==='runs')notice(e.message,true);}}
function renderMix(){$('export').hidden=false;$('mix-meta').textContent=`${result.user_id} · ${result.recommendations.length} results · ${Math.round(result.alpha*100)}% discovery · ${result.alpha_mode} balance`;$('mix-results').className='';$('mix-results').innerHTML=result.recommendations.length?table(['Track / artist','Stream','Score',''],result.recommendations.map((r,index)=>`<tr><td>${track(r)}</td><td><span class="badge ${r.kind==='novelty'?'':'pending'}">${esc(r.kind==='novelty'?'Discovery':'Nostalgia')}</span></td><td>${Number(r.score).toFixed(4)}</td><td><button class="secondary" data-explain="${index}">Why this track? ↗</button></td></tr>`)):'<div class="empty">No positive candidates for this blend. Try automatic balance or add compatible tags.</div>';document.querySelectorAll('[data-explain]').forEach(button=>button.onclick=()=>explain(Number(button.dataset.explain)));}
function explain(index){const r=result.recommendations[index],fields=Object.fromEntries(result.explanation_fields.map((name,i)=>[name,r.explanation_tuple[i]]));$('explanation-content').innerHTML=`<div class="eyebrow">THE REASON BEHIND THE RANK</div><h2>${esc(r.track_name||r.item_id)}</h2><p>${esc(r.artist_name||'')}</p><p>${esc(r.reason)}</p><h3>How the score adds up</h3>${[['Discovery',fields.contribution_a],['Nostalgia',fields.contribution_b]].map(([name,value])=>`<div class="contribution"><div class="row"><span>${name}</span><strong>${Number(value).toFixed(4)}</strong></div><meter min="0" max="1" value="${Number(value)}">${Number(value).toFixed(4)}</meter></div>`).join('')}<div class="status-line"><strong>Final score</strong><strong>${Number(r.score).toFixed(4)}</strong></div><h3>Shared tags</h3><div class="tags">${fields.shared_tags.length?fields.shared_tags.map(t=>`<span>${esc(t)}</span>`).join(''):'<span>No shared tag evidence</span>'}</div>${r.nostalgia_evidence?`<div class="status-line"><span>Historical plays</span><b>${fmt(fields.historical_plays)}</b></div><div class="status-line"><span>Days since last play</span><b>${Number(fields.days_dormant).toFixed(1)}</b></div><div class="status-line"><span>Tag similarity</span><b>${r.nostalgia_evidence.tag_similarity.toFixed(4)}</b></div>`:''}<p class="fine">These values explain the score calculation, not a causal reason for liking a track.</p>`;$('explanation').showModal();}
$('close-explanation').onclick=()=>$('explanation').close();$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='reprise-mix.json';a.click();URL.revokeObjectURL(url);};
(async()=>{try{state=await api('/api/status');readiness();show(location.hash.slice(1));await users();await poll();setInterval(()=>{if(page==='runs'||jobs.some(j=>j.status==='running'))poll();},3000);}catch(e){notice(e.message,true);}})();
